# Generated by Django 5.2.13 on 2026-04-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(default='', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='senha_embarcado',
            field=models.CharField(default='', help_text='Senha numérica de 8 dígitos', max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SERVIDOR', 'Servidor'), ('TERCEIRIZADO', 'Terceirizado')], default='ALUNO', max_length=20),
        ),
    ]
