# Generated by Django 5.2.13 on 2026-08-09 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data']},
        ),
        # migrations.RemoveField(
        #     model_name='emprestimo',
        #     name='chaves',
        # ),
        # migrations.RemoveField(
        #     model_name='emprestimo',
        #     name='data_hora',
        # ),
        migrations.AddField(
            model_name='emprestimo',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('SOLICITADO', 'Solicitado'), ('DEVOLVIDO', 'Devolvido')], default='NOVO', max_length=10),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='controle_chaves.usuario'),
        ),
    ]
