# Generated by Django 5.2.13 on 2026-08-09 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0002_alter_emprestimo_options_remove_emprestimo_chaves_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='chaves',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='data_hora',
        ),
        migrations.RemoveField(
            model_name='emprestimo',
            name='usuario',
        ),
    ]
