# Generated by Django 5.2.13 on 2026-07-27 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0002_usuario_email_usuario_senha_embarcado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chave',
            name='uid_rfid',
            field=models.CharField(blank=True, help_text='Código UID da Tag RFID', max_length=50, null=True, unique=True),
        ),
    ]
