# Generated by Django 5.2.13 on 2026-08-09 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0003_remove_emprestimo_chaves_remove_emprestimo_data_hora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='controle_chaves.usuario'),
            preserve_default=False,
        ),
    ]
