# Generated by Django 5.2.13 on 2026-07-28 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0003_chave_uid_rfid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='uid_rfid',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='senha_embarcado',
        ),
    ]
