# Generated by Django 5.2.13 on 2026-08-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0004_remove_chave_uid_rfid_remove_usuario_senha_embarcado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='disponivel',
        ),
        migrations.AddField(
            model_name='chave',
            name='bloco',
            field=models.CharField(choices=[('A', 'Bloco A'), ('B', 'Bloco B'), ('C', 'Bloco C'), ('D', 'Bloco D')], default='A', max_length=1, verbose_name='Bloco/Local'),
        ),
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
