# Generated by Django 5.2.13 on 2026-08-09 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0004_emprestimo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimo',
            name='chaves',
            field=models.ManyToManyField(blank=True, related_name='emprestimos', to='controle_chaves.chave'),
        ),
    ]
