# Generated by Django 5.2.13 on 2026-08-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0005_remove_chave_disponivel_chave_bloco_alter_chave_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chave',
            name='bloco',
        ),
        migrations.AddField(
            model_name='chave',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='chave',
            name='nome',
            field=models.CharField(max_length=50),
        ),
    ]
