# Generated by Django 5.2.13 on 2026-08-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0005_emprestimo_chaves'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='status',
            field=models.CharField(choices=[('NOVO', 'Novo'), ('SOLICITADO', 'Solicitado'), ('DEVOLVIDO', 'Devolvido'), ('REPASSADO', 'Repassado')], default='NOVO', max_length=10),
        ),
    ]
