# Generated by Django 5.2.13 on 2026-08-28 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0006_alter_emprestimo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='chaves',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='chave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to='controle_chaves.chave'),
        ),
    ]
