# Generated by Django 5.2.13 on 2026-09-25 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0008_emprestimo_data_devolucao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='vinculo',
            field=models.CharField(choices=[('ALUNO', 'Aluno'), ('PROFESSOR', 'Professor'), ('SERVIDOR', 'Servidor'), ('TERCEIRIZADO', 'Terceirizado'), ('GUARITA', 'Guarita'), ('ADMIN', 'Administrador')], default='ALUNO', max_length=20),
        ),
    ]
