# Generated by Django 5.2.13 on 2026-09-29 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_chaves', '0009_usuario_user_alter_usuario_vinculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.CharField(max_length=255)),
                ('lida', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('chave', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='controle_chaves.chave')),
            ],
        ),
    ]
